config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  get 'home/index'

  resources :students

  # get 'students/index'

  # get 'students/show'

  # get 'students/new'

  # post 'students/create'

  # post 'students/update'

  # delete 'students/destroy'

  get 'bukatsues/index'

  get 'bukatsues/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bukatsu.rb
class Bukatsu < ApplicationRecord
	has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :bukatsu
	validates :name, presence: true
	validates :grade, presence: true
	validates :introduction, presence: true
	validates :bukatsu_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bukatsues_controller.rb
class BukatsuesController < ApplicationController
  def index
  	@bukatsues = Bukatsu.all
  end

  def show
  	@buins = Bukatsu.find(params[:id]).students
  	@bukatsu = Bukatsu.find(params[:id])
  	# @buins = @bukatsu.students
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def index
  	require 'uri'
  	require 'json'

  	# iTunesAPI
 #  	uri = URI.parse('https://itunes.apple.com/search?term=%E3%83%AF%E3%83%B3%E3%82%AA%E3%82%AF&media=music&country=jp&lang=ja_jp&limit=20')
 #  	json = Net::HTTP.get(uri)
 #  	info = JSON.parse(json)

	# @contents = info['results'].sort{|aa, bb| aa['releaseDate'] <=> bb['releaseDate'] }

	# テスト
  	# @tracknames =  @contents.map { |content| content['trackName'] }
  	# @release_dates = @contents.map { |content| content['releaseDate'] }
   # 	@release_dates = @contents.map { |content| content['artworkUrl60'] }

   # sakeAPI
   uri = URI.parse('https://www.sakenote.com/api/v1/sakes?token=d72690b6c614a1a749466aaa5eefc9e883003ac8&prefecture_code=13')
   sake_json = Net::HTTP.get(uri)
   sake_info = JSON.parse(sake_json)
# binding.pry
	@sakes = sake_info['sakes']
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    # @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "部活登録完了！"
      redirect_to @student
    else
      flash[:warning] = "登録失敗"
      redirect_to new_student_path
    end
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash[:success] = "修正しました！"
      redirect_to @student
    else
      flash[:warning] = "修正に失敗しました"
      render 'edit'
    end
  end

  def destroy
    # binding.pry
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private

    def student_params
      params.require(:student).permit(:name, :grade, :introduction, :bukatsu_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bukatsues_helper.rb
module BukatsuesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/bukatsues/index.html.erb
<h1>部活一覧</h1>

<% @bukatsues.each do |bu| %>
	<p><%= link_to bu.name, bukatsues_show_path(id: bu.id) %></p>
<% end -%>

app/views/bukatsues/show.html.erb
<h1><%= @bukatsu.name %></h1>
<h2>所属人数：<%= @buins.size %>名</h2>
<% @buins.each do |buin| %>
	<ul>
		<li>名前：<%= link_to buin.name, student_path(buin.id) %> / <%= buin.grade %>年生 / 特徴：<%= buin.introduction %></li>
	</ul>
<% end -%>

app/views/home/index.html.erb
<% if @contents.present? %>

	<h1><%= @contents[0]['artistName'] %></h1>

	<% @contents.each do |content| %>
	<ul>
		<li>title: <%= content['trackName'] %></li>
		<li>released date: <%= content['releaseDate'][0,10] %></li>
		<li><img src="<%= content['artworkUrl60'] %>"></li>
	</ul>
	<% end -%>
<% end -%>




<h1>美しい日本酒</h1>

<% @sakes.each do |sake| %>
	<ul>
		<li>名前： <%= sake['sake_name'] %></li>
		<li>ふりがな <%= sake['sake_furigana'] %></li>
		<li>酒造店： <%= sake['maker_name'] %></li>
		<li>酒造店URL： <a href="<%= sake['maker_url'] %>"><%= sake['maker_url'] %></a></li>
	</ul>
<% end -%>

app/views/home/top.html.erb
<h1>ようこそ部活動アプリへ</h1>

<h2><%= link_to "部活に参加する", new_student_path %></h2>
<h2><%= link_to "部活一覧を見る", bukatsues_index_path %></h2>

<br><br>

<h2><%= link_to "部活参加済生徒名簿", students_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BukatsuApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<div><%= f.label :name %><%= f.text_field :name %></div>
<div><%= f.label :grade %><%= f.text_field :grade %></div>
<div><%= f.label :introduction %><%= f.text_area :introduction %></div>
<div>
	<%= f.label :bukatsu_id %>
	<!-- f.collection_select <属性名>, <表示させるモデル>, <渡す値>, <モデルから表示させるカラム>, prompt: <デフォルト表示文字> -->
	<%= f.collection_select :bukatsu_id, Bukatsu.all, :id, :name, prompt: "部活動選択" %></div>
<%= f.submit %>

app/views/students/edit.html.erb
<%= flash[:warning] %>
<h1>部活参加フォームの修正</h1>

<%= form_for :student, url: student_path, method: :patch do |f| %>

	<%= render partial: 'form', locals: {:f => f} %>

<% end -%>
<%= link_to "戻る", :back %>

app/views/students/index.html.erb
<h1>部活参加済生徒名簿</h1>

<% @students.each do |student| %>
	<table>
	<tr>
		<td>名前：<%= student.name %> / </td>
		<td>学年：<%= student.grade %>年生 / </td>
		<td>詳細：<%= student.introduction %> / </td>
		<td>部活：<%= student.bukatsu.name %></td>
		<td><%= link_to "修正する", edit_student_path(student) %></td>
		<td><%= link_to "削除する", student_path(student), method: :delete, data: { confirm: 'Sure?' } %></td>
		<br>
	</tr>
	</table>
<% end -%>

app/views/students/new.html.erb
<%= flash[:warning] %>
<h1>部活参加フォーム</h1>
<!-- routes が resoucesを使っている場合は、@studentを渡すだけで、使うviewに合わせてRailsでうまく処理してくれる -->

<!-- studentモデルを指定し、createのパスに送信する -->
<%= form_for :student, url: students_path do |f| %>
	<%= render partial: 'form', locals: {:f => f} %>
<% end -%>

<%= link_to "戻る", :back %>

app/views/students/show.html.erb
<%= flash[:success] %>

<h1><%= @student.name %></h1>
<p><%= @student.grade %>年生</p>
<p>自己紹介：
	<br>
	<%= @student.introduction %></p>
<p>部活：<strong><%= @student.bukatsu.name %></strong></p>

<%= link_to "トップに戻る", root_path %>
<br>
<%= link_to "部活一覧を見る", bukatsues_index_path %>
<br>
<%= link_to "部活動参加生徒名簿を見る", students_path %>